# Generated by Django 4.2.16 on 2025-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_info", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financeinfo",
            name="image",
        ),
        migrations.CreateModel(
            name="MetalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metal_type",
                    models.CharField(
                        choices=[("gold", "금"), ("silver", "은")], max_length=10
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.FloatField()),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("metal_type", "date")},
            },
        ),
    ]
