# Generated by Django 4.2.16 on 2025-05-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('sector_code', models.CharField(blank=True, max_length=20, null=True)),
                ('sector_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=200)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('dcls_month', models.CharField(max_length=10)),
                ('etc', models.JSONField(blank=True, null=True)),
                ('max_rate', models.FloatField(default=0)),
                ('sector_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_products', to='deposits.bank')),
            ],
        ),
    ]
