# Generated by Django 4.2.16 on 2025-05-23 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("fin_co_no", models.TextField(primary_key=True, serialize=False)),
                ("kor_co_nm", models.TextField()),
                ("sector_code", models.TextField(blank=True, null=True)),
                ("sector_name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DepositProduct",
            fields=[
                ("fin_prdt_cd", models.TextField(primary_key=True, serialize=False)),
                ("fin_prdt_nm", models.TextField()),
                ("join_way", models.TextField(blank=True, null=True)),
                ("mtrt_int", models.TextField(blank=True, null=True)),
                ("spcl_cnd", models.TextField(blank=True, null=True)),
                ("join_member", models.TextField(blank=True, null=True)),
                ("join_deny", models.TextField(blank=True, null=True)),
                ("etc_note", models.TextField(blank=True, null=True)),
                ("max_limit", models.IntegerField(blank=True, null=True)),
                ("dcls_strt_day", models.TextField()),
                ("dcls_end_day", models.TextField(blank=True, null=True)),
                ("fin_co_subm_day", models.TextField()),
                ("sector_code", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(default=list)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="deposits.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavingProduct",
            fields=[
                ("fin_prdt_cd", models.TextField(primary_key=True, serialize=False)),
                ("fin_prdt_nm", models.TextField()),
                ("join_way", models.TextField(blank=True, null=True)),
                ("mtrt_int", models.TextField(blank=True, null=True)),
                ("spcl_cnd", models.TextField(blank=True, null=True)),
                ("join_member", models.TextField(blank=True, null=True)),
                ("join_deny", models.TextField(blank=True, null=True)),
                ("etc_note", models.TextField(blank=True, null=True)),
                ("max_limit", models.IntegerField(blank=True, null=True)),
                ("dcls_strt_day", models.TextField()),
                ("dcls_end_day", models.TextField(blank=True, null=True)),
                ("fin_co_subm_day", models.TextField()),
                ("sector_code", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(default=list)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings",
                        to="deposits.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intr_rate_type", models.TextField()),
                ("intr_rate_type_nm", models.TextField()),
                ("save_trm", models.TextField()),
                ("intr_rate", models.TextField(blank=True, null=True)),
                ("intr_rate2", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saving_options",
                        to="deposits.savingproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intr_rate_type", models.TextField()),
                ("intr_rate_type_nm", models.TextField()),
                ("save_trm", models.TextField()),
                ("intr_rate", models.TextField(blank=True, null=True)),
                ("intr_rate2", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_options",
                        to="deposits.depositproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavingSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deposits.savingproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "product")},
            },
        ),
        migrations.CreateModel(
            name="DepositSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deposits.depositproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "product")},
            },
        ),
    ]
