# Generated by Django 4.2.16 on 2025-05-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='etc',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
