# Generated by Django 4.2.16 on 2025-05-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("deposits", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribed_deposits",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_subscribers",
                to="deposits.depositproduct",
                verbose_name="가입한 정기예금 상품",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_savings",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_subscribers",
                to="deposits.savingproduct",
                verbose_name="가입한 정기적금 상품",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="accounts_user_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
