# Generated by Django 4.2.16 on 2025-05-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="saved_videos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
