# Generated by Django 4.2.16 on 2025-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_saved_channels_user_saved_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="나이"),
        ),
        migrations.AddField(
            model_name="user",
            name="annual_income",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="연봉 (원)"),
        ),
        migrations.AddField(
            model_name="user",
            name="assets",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="자산 (원)"),
        ),
    ]
