# Generated by Django 4.2.16 on 2025-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_age_user_annual_income_user_assets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribed_deposits",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscribed_savings",
        ),
        migrations.AddField(
            model_name="user",
            name="investment_tendency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_conservative", "매우 보수적"),
                    ("conservative", "보수적"),
                    ("moderate", "중립적"),
                    ("aggressive", "적극적"),
                    ("very_aggressive", "매우 적극적"),
                ],
                max_length=20,
                null=True,
                verbose_name="투자성향",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_bank",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="선호 은행 코드"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="savings_tendency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("conservative", "안정형"),
                    ("moderate", "균형형"),
                    ("aggressive", "적극형"),
                ],
                max_length=20,
                null=True,
                verbose_name="저축성향",
            ),
        ),
    ]
