# Generated by Django 4.2.16 on 2025-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0001_initial"),
        ("accounts", "0005_remove_user_subscribed_deposits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribed_deposits",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                through="deposits.DepositSubscription",
                to="deposits.depositproduct",
                verbose_name="가입한 정기예금 상품",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_savings",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                through="deposits.SavingSubscription",
                to="deposits.savingproduct",
                verbose_name="가입한 정기적금 상품",
            ),
        ),
    ]
