# Generated by Django 4.2.16 on 2025-05-27 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_academy', '0002_choice_question_questioncategory_userquizattempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'Question Categories'},
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='finance_academy.questioncategory'),
        ),
    ]
