# Generated by Django 4.2.16 on 2025-05-27 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance_academy", "0004_assessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("youth", "청소년"),
                            ("adult_basic", "성인 기본"),
                            ("adult_advanced", "성인 심화"),
                        ],
                        max_length=20,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=20, unique=True)),
                ("grade", models.CharField(max_length=5)),
                ("score", models.IntegerField()),
                ("total_questions", models.IntegerField(default=10)),
                ("file_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "difficulty")},
            },
        ),
    ]
